insert into
public.customers (customer_name, house_number, street_name, town, postcode, country, email, reference, discount)
values
('Hillcrest', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Parc Owles', '', 'Casita Serena', 'Parc Owles, Carbis Bay', 'TR26 2RE', 'UK', '', 'Parc Owles Design & Development Ltd', 0),
('CH1', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('CH2', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Glas Mor', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('20 Barnaloft', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Atlantic Blue', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Coastal Seascape ', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Tinhay April throw', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Tinhay', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Zennor', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('15 Digey', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Lahaina', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('6 Sunnyside', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Artists Light', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('18 TC', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Rose Cottage', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Ocean Seascape', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Treloweth', '53', 'Higher Bosskerris', 'Carbis Bay', 'TR26 2TL', 'UK', '', 'St Ives Housekeeping Co', 0),
('Kiama', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Ahoy there', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Harbour Beach Cottage', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Barnoon villa', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Painters', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Shearwater', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('4 Salt', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Porthia Penthouse', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Old Boswednack', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('Enys Cottage', '', 'Park Avenue', 'St Ives', 'TR26 2DN', 'UK', '', 'Orange Roofs', 0),
('16 Ros Lyn', '', '', '', '', 'UK', 'tomjterry89@gmail.com', 'Thomas Terry', 0),
('Foxgloves', '', '', '', '', 'UK', 'foxgloves.carbisbay@gmail.com', 'John and David Foxgloves', 0),
('18 Virgin St', '', '', '', '', 'UK', 'mackieainslie@gmail.com', 'Ainsley Fowler', 0),
('Ocean View', '', '', '', '', 'UK', 'kateydeseta@yahoo.co.uk', 'Sally Deseta', 0),
('Cobbles', '', '', '', '', 'UK', 'stives.invoices@aspects.co.uk', 'Aspects Holidays (St Ives)', 0),
('Garden House', '', '', '', '', 'UK', 'kateydeseta@yahoo.co.uk', 'Kate Deseta', 0),
('Beachcroft', '', 'St Ives Road', 'Carbis Bay', 'TR26 2RT', 'UK', '', 'Carbis Bay Holidays', 0),
('Pebbles', '', 'St Ives Road', 'Carbis Bay', 'TR26 2RT', 'UK', '', 'Carbis Bay Holidays', 0),
('Mincarlo', '', 'St Ives Road', 'Carbis Bay', 'TR26 2RT', 'UK', '', 'Carbis Bay Holidays', 0),
('Toms', '', 'St Ives Road', 'Carbis Bay', 'TR26 2RT', 'UK', '', 'Carbis Bay Holidays', 0),
('Bayview', '', 'St Ives Road', 'Carbis Bay', 'TR26 2RT', 'UK', '', 'Carbis Bay Holidays', 0),
('Lighthouse', '', 'St Ives Road', 'Carbis Bay', 'TR26 2RT', 'UK', '', 'Carbis Bay Holidays', 0),
('Hawkes View', '', 'Hawkes View', 'Pannier Lane, Carbis Bay', 'TR26 2RF', 'UK', '', 'Chris Cooper', 0),
('8 Salt', '', 'No 8 Salt', 'Belyars Lane, St Ives', 'TR26 2BZ', 'UK', '', 'Wendy Cooper', 0),
('Riviere', '26', 'Wheal Alfred Road', 'Hayle, ', 'TR27 5JU', 'UK', '', 'Jane Marks', 0),
('Flat 1&2 Rhymey ', '', '', '', '', 'UK', '', '', 0),
('1 Sunnyside', '1', 'Sunnyside', 'Back Road East, St Ives', 'TR26 1PE', 'UK', '', 'Di Pollock', 0),
('Tor-mewan', '', 'Tor-mewan', 'Higher Trewidden Road, St Ives', 'TR26 2DP', 'UK', '', 'Amanda Fox', 0),
('Green Clean', '', 'Wheal Venture Rd', 'Carbis Bay', 'TR26 2PQ', 'UK', '', 'Victoria Read', 0),
('Topaz', '', 'Wheal Venture Rd', 'Carbis Bay', 'TR26 2PQ', 'UK', '', 'Harbour Housekeeping', 0),
('Serena', '', 'Wheal Venture Rd', 'Carbis Bay', 'TR26 2PQ', 'UK', '', 'Harbour Housekeeping', 0),
('10 Windsor', '10', 'Windsor Terrace', 'Penzance', 'TR18 2PX', 'UK', '', 'Susie Huntington', 0),
('Woodstock', '', 'Woodstock Glamping', 'Woodstock House, Rosudgeon', 'TR20 9QA', 'UK', '', 'Sarah Arrowsmith', 0),
('Uplands', '', 'Uplands,', 'Chy-an-Dour road,, Praa Sands.', 'TR20 9SY', 'UK', '', 'Jane Adams', 0),
('Suncroft', '6', 'Broadwalk,', 'Helston', 'TR13 0DJ', 'UK', '', 'Davina Cox', 0),
('Stone Croft', '', 'Stone croft', 'Praa sands', 'TR20 9TA', 'UK', '', 'Sue Cassettari', 0),
('Kenegie', '', 'Kenegie Home Farm', 'Gulval, Cornwall', 'TR20 8YN', 'UK', '', 'Noelle Rorke', 0),
('Miramar', '', '', '', '', 'UK', 'stives.invoices@aspects.co.uk', 'Aspects Holidays', 0),
('Wayside', '3', 'Fraddam Road', 'Hayle', 'TR27 5EW', 'UK', '', 'Louise Dean', 0),
('Clodgy', '3', 'Clodgy View', 'St Ives', 'TR26 1JG', 'UK', '', 'Emma Smith', 0),
('8 Barnaloft', '8', 'Barnaloft', 'St Ives, ', '', 'UK', '', 'Tamsyn Williams', 0),
('Tinners Arms', '', 'The Tinners Arms', 'Zennor, St Ives', 'TR26 3BY', 'UK', '', 'The White House', 0);

insert into
public.items (item_name, price, stock, loaned_out)
values
('superking bed set', 11.89, 100, 20),
('king bed set', 10.01, 90, 13),
('double bed set', 10.01, 88, 12),
('single bed set', 7.80, 120, 33),
('pillow protectors', 2.25, 25, 2),
('single mattress protectors', 2.50, 10, 2),
('double mattress protectors', 3.50, 10, 2),
('king mattress protectors', 3.50, 10, 2),
('super king mattress protectors', 3.50, 10, 2),
('bath sheet', 2.37, 50, 17),
('bath mat', 2.25, 50, 13),
('hand towel', 1.19, 112, 56),
('tea towel', 0.71, 120, 73),
('oven gloves', 1.19, 30, 5),
('cushion cover', 2.70, 10, 0),
('throw', 4.86, 12, 1),
('dressing gown', 4.32, 20, 10),
('dog towel', 2.05, 10, 5);




